services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - vol-dotpix-rabbitmq:/var/lib/rabbitmq/
    networks:
      - dotpix-rabbitmq
  
  db:
    image: postgres
    container_name: dotpix_db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - vol-dotpix-dbpostgres:/var/lib/postgresql/data
    networks:
      - dotpix-db
  
  api:
    image: dotpix-api
    container_name: dotpix_api
    restart: always
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    build:
      context: .
      dockerfile: DotPixApi/Dockerfile
    ports:
      - 8080:8080
    environment:
      APPPARAMETERS__RABBITMQ__HOSTNAME: rabbitmq
    networks:
      - dotpix-rabbitmq
      - dotpix-db
  
  paymentworker1:
    image: dotpix-payment-worker
    container_name: payment-worker1
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
    build:
      context: .
      dockerfile: DotPixPaymentWorker/Dockerfile
    environment:
      APPPARAMETERS__WORKERNAME: Payment Worker 1
      APPPARAMETERS__RABBITMQ__HOSTNAME: rabbitmq
    networks:
      - dotpix-net
      - dotpix-rabbitmq
      - dotpix-db
  
  paymentworker2:
    image: dotpix-payment-worker
    container_name: payment-worker2
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
    build:
      context: .
      dockerfile: DotPixPaymentWorker/Dockerfile
    environment:
      APPPARAMETERS__WORKERNAME: Payment Worker 2
      APPPARAMETERS__RABBITMQ__HOSTNAME: rabbitmq
    networks:
      - dotpix-net
      - dotpix-rabbitmq
      - dotpix-db
        
  conciliationworker1:
    image: dotpix-conciliation-worker
    container_name: conciliation-worker1
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
    build:
      context: .
      dockerfile: DotPixConciliationWorker/Dockerfile
    environment:
      APPPARAMETERS__WORKERNAME: Conciliation Worker 1
      APPPARAMETERS__RABBITMQ__HOSTNAME: rabbitmq
    networks:
      - dotpix-net
      - dotpix-rabbitmq
      - dotpix-db
  
  pspapi:
    image: psp-api-mock
    container_name: pspapi
    build:
      context: .
      dockerfile: PspApiMock/Dockerfile
    ports:
      - 8081:8080
    networks:
      - dotpix-net

networks:
  dotpix-db:
    driver: bridge
    name: net-dotpix-db
  dotpix-net:
    driver: bridge
    name: net-dotpix
  dotpix-rabbitmq:
    driver: bridge
    name: net-dotpix-rabbitmq

volumes:
  vol-dotpix-dbpostgres:
  vol-dotpix-rabbitmq:
