global:
  scrape_interval: 5s
  external_labels:
    monitor: "node"
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "prometheus:9090" ]
  - job_name: "node-exporter"
    static_configs:
      - targets: [ "node-exporter:9100" ]
  - job_name: "postgres-exporter"
    static_configs:
      - targets: [ "postgres-exporter:9187" ]
  - job_name: "asp-net-exporter"
    static_configs:
      - targets: [ "localhost:5200" ]