services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - dotpix-pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - dotpix-db

volumes:
  dotpix-pgdata:

networks:
  dotpix-db:
    driver: bridge
    name: dotpix-db